---
- name: ensure redis is at the latest version
  apt: pkg=redis-server state=latest
- name: ensure redis is running
  service: name=redis-server state=started

- name: install redis module for backup script
  pip: name=redis state=present virtualenv=/home/btl/python
- name: install hiredis module for backup script
  pip: name=hiredis state=present virtualenv=/home/btl/python
- name: install pyrax module for backup script
  pip: name=pyrax state=present virtualenv=/home/btl/python

- name: set up cron job for backups
  cron: name="backups" minute="*/10" job="REDIS_HOST={{ ansible_eth1['ipv4']['address'] }} /home/btl/python/bin/python /home/btl/site/scripts/backup.py" state=present